### ISSUE TITLE
Error running with Java 11

### ISSUE THREAD

**Issue by praneetloke** [armory-io/plugin-metadata-updater#1]
I just encountered an error while trying to release a new version of our Pulumi plugin for Spinnaker.

```
ERROR: JAVA_HOME is set to an invalid directory: /opt/hostedtoolcache/jdk/11.0.10/x64

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

This was the env map with which it ran:

```
  with:
    metadata: build/distributions/plugin-info.json
    binary_url: https://github.com/pulumi/spinnaker-preconfigured-job-plugin/releases/download/v0.1.0/spinnaker-preconfigured-job-plugin-v0.1.0.zip
    metadata_repo_url: https://github.com/pulumi/spinnaker-plugins-repository
  env:
    PLUGINS_REPOSITORY: spinnaker-plugins-repository
    JAVA_HOME_11.0.10_x64: /opt/hostedtoolcache/jdk/11.0.10/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.10/x64
    JAVA_HOME_11_0_10_X64: /opt/hostedtoolcache/jdk/11.0.10/x64
    GITHUB_OAUTH: ***
```

Any idea as to how to fix this? I am also not sure if this is a bug in the action.

**EDIT:** As a workaround, explicitly setting `JAVA_HOME` to an empty value `""` in the `env` map seems to work.
